name: Build and Deploy
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps: 
      env:
        NEOCITIES_KEY: {{ secrets.NEOCITIES_KEY }}
      - name: checkout code
        uses: actions/checkout@v4
      - name: set up code
        uses: actions/setup-node@v4
      - name: install dependencies
        run: npm install
      - name: run build script
        run: npm run build
      - name: upload folder
        run: curl -H "Authorization: Bearer $NEOCITIES_KEY" \
https://neocities.org/api/info
