name: Build and Deploy
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps: 
      - name: checkout code
        uses: actions/checkout@v4
      - name: set up code
        uses: actions/setup-node@v4
      - name: install dependencies
        run: npm install
      - name: run build script
        run: npm run build
      - name: list directories
        run: ls -la

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: checkout code
        uses: actions/checkout@v4
      - name: print directories
        run: ls -a
