name: Build and Deploy
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps: 
      - name: checkout code
        uses: actions/checkout@v4
      - name: set up code
        uses: actions/setup-node@v4
      - name: install dependencies
        run: npm install
      - name: build blog listing
        run: |
          ./infra/list-posts.sh
      - name: run build script
        run: npm run build
      - name: upload folder
        env:
          NEOCITIES_KEY: ${{ secrets.NEOCITIES_KEY }}
        run: |
          ./infra/upload-website.sh
